### ISSUE TITLE
Can you make me a maintainer?

### ISSUE THREAD

**Issue by dermorz** [ZephyrBlu/zephyrus-sc2-parser#30]
Hey there,

I might be one of the few actively using your library and I would be glad to actively maintain it. This means reviewing and merging community contributions and also keeping it up to date with new Starcraft builds.

We can discuss details and what you have/had in mind for the future of this project if you want.

I might also have some minor fixes in the pipeline, but would also discuss those with you first.

Best regards

**Comment by ZephyrBlu** [comment]
Have zero problems with this. This repo deserves more love. I added you as a collaborator, which I think means you should be able to do stuff like commit, merge PRs, etc.

I'm more than happy for you to maintain the repo how you see fit. I have moved on from this project for now because these days I'm using a basic Rust parser that I wrote for performance reasons and I'm not as focused on the deep details that this parser extracts.

If you have any major changes in mind maybe we can talk about that, but for minor changes I don't think you need to run anything by me 😄.

Not sure how this would work for updating the PyPI package though 😕. Maybe I could create a new account and share the password with you?

**Comment by dermorz** [comment]
Oh, thanks very much.

Regarding PyPI we could setup a github action like https://github.com/marketplace/actions/pypi-publish and you set the `PYPI_API_TOKEN` in https://github.com/ZephyrBlu/zephyrus-sc2-parser/settings/secrets/actions. No need for sharing credentials. :)

**Comment by ZephyrBlu** [comment]
That sounds good! What do I need to do for that? Generate an API token on
PyPI?

**Comment by dermorz** [comment]
I think so. Then you set it up in the repo settings and I can take care of the rest.

**Comment by ZephyrBlu** [comment]
Cool, I’ll do that tomorrow.

**Comment by dermorz** [comment]
Alright, no hurry. :)

See here: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github

**Comment by dermorz** [comment]
Closing this as resolved.
